// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxyN5SZ99j2mPKgeo17XM3k0v8dGKOxOc',
    appId: '1:880067110972:web:9d1caaa01c6f35348f7b39',
    messagingSenderId: '880067110972',
    projectId: 'shop-easy-5658',
    authDomain: 'shop-easy-5658.firebaseapp.com',
    storageBucket: 'shop-easy-5658.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0UCE206EYKEk5W0_cUFvDW4fFApSEkII',
    appId: '1:880067110972:android:6da4b5aad05d41348f7b39',
    messagingSenderId: '880067110972',
    projectId: 'shop-easy-5658',
    storageBucket: 'shop-easy-5658.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5dOBMI4eWenqGcc6Z2SZOt4iBxIFNpig',
    appId: '1:880067110972:ios:5ce0a3edae01b7328f7b39',
    messagingSenderId: '880067110972',
    projectId: 'shop-easy-5658',
    storageBucket: 'shop-easy-5658.firebasestorage.app',
    iosBundleId: 'com.example.shopEasy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5dOBMI4eWenqGcc6Z2SZOt4iBxIFNpig',
    appId: '1:880067110972:ios:5ce0a3edae01b7328f7b39',
    messagingSenderId: '880067110972',
    projectId: 'shop-easy-5658',
    storageBucket: 'shop-easy-5658.firebasestorage.app',
    iosBundleId: 'com.example.shopEasy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxyN5SZ99j2mPKgeo17XM3k0v8dGKOxOc',
    appId: '1:880067110972:web:1e0214bc2d8f41f18f7b39',
    messagingSenderId: '880067110972',
    projectId: 'shop-easy-5658',
    authDomain: 'shop-easy-5658.firebaseapp.com',
    storageBucket: 'shop-easy-5658.firebasestorage.app',
  );
}
